modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="obimod"
version="1.0"
displayName="Obsidian Tools"


logoFile="obi_sword.png"
credits="Loyodea"
authors="Loyodea"
description='''
A 1.19 mod that adds Obsidian tools to minecraft!

'''
